// Auto-generated by `puffgres generate`. Do not edit.
// Source: public.smart_buyer

import { parseRow as parseRowInternal, parseRows as parseRowsInternal, type Column } from "../../utils/puffgres";

export const columns = [
  { name: "id", type: "string" },
  { name: "buyer_name", type: "string" },
  { name: "buyer_id", type: "string" },
] as const satisfies readonly Column[];

export const parseRow = (cols: (string | null)[]) => parseRowInternal(columns, cols);
export const parseRows = (rows: (string | null)[][]) => parseRowsInternal(columns, rows);
