use tokio_postgres::Client;

use crate::{PgError, Result, connect::quote_identifier};

pub const PUFFGRES_SCHEMA: &str = "puffgres";

const STATE_TABLES: [&str; 5] = [
    "configs",
    "streaming_checkpoints",
    "backfill_progress",
    "dlq",
    "runtime_state",
];

pub async fn ensure_schema(client: &Client, schema_name: &str) -> Result<()> {
    let query = format!(
        "CREATE SCHEMA IF NOT EXISTS {}",
        quote_identifier(schema_name)
    );
    client
        .batch_execute(&query)
        .await
        .map_err(|e| PgError::from_query_err(format!("Failed to ensure schema '{schema_name}'"), &e))
}

pub async fn schema_exists(client: &Client, schema_name: &str) -> Result<bool> {
    let row = client
        .query_one(
            "SELECT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = $1)",
            &[&schema_name],
        )
        .await
        .map_err(|e| {
            PgError::from_query_err(format!("Failed to check schema '{schema_name}'"), &e)
        })?;
    Ok(row.get(0))
}

pub async fn ensure_state_tables(client: &Client, schema_name: &str) -> Result<()> {
    let schema = quote_identifier(schema_name);
    let ddl = format!(
        r#"
        CREATE TABLE IF NOT EXISTS {schema}.configs (
            name TEXT PRIMARY KEY,
            namespace TEXT NOT NULL UNIQUE,
            content_hash TEXT NOT NULL,
            transform_hash TEXT,
            applied_at BIGINT NOT NULL,
            tombstone_applied_at BIGINT,
            namespace_prefix TEXT
        );

        CREATE TABLE IF NOT EXISTS {schema}.streaming_checkpoints (
            config_name TEXT PRIMARY KEY
                REFERENCES {schema}.configs(name) ON DELETE CASCADE,
            lsn BIGINT NOT NULL,
            events_processed BIGINT NOT NULL DEFAULT 0,
            updated_at BIGINT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS {schema}.backfill_progress (
            config_name TEXT PRIMARY KEY
                REFERENCES {schema}.configs(name) ON DELETE CASCADE,
            last_id TEXT,
            total_rows BIGINT,
            processed_rows BIGINT NOT NULL DEFAULT 0,
            status TEXT NOT NULL
                CHECK (status IN ('pending', 'in_progress', 'completed', 'failed')),
            started_at BIGINT,
            completed_at BIGINT,
            error_message TEXT,
            watermark_lsn BIGINT
        );

        CREATE TABLE IF NOT EXISTS {schema}.dlq (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            config_name TEXT NOT NULL
                REFERENCES {schema}.configs(name) ON DELETE CASCADE,
            lsn BIGINT NOT NULL,
            doc_id TEXT,
            error_message TEXT NOT NULL,
            error_kind TEXT NOT NULL
                CHECK (error_kind IN ('retryable', 'permanent')),
            retry_count INTEGER NOT NULL DEFAULT 0,
            created_at BIGINT NOT NULL,
            last_retry_at BIGINT,
            permanent_at BIGINT,
            operation TEXT
                CHECK (operation IN ('insert', 'update', 'delete'))
        );

        CREATE INDEX IF NOT EXISTS idx_dlq_config_name
            ON {schema}.dlq(config_name);
        CREATE INDEX IF NOT EXISTS idx_dlq_error_kind
            ON {schema}.dlq(error_kind);

        CREATE TABLE IF NOT EXISTS {schema}.runtime_state (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at BIGINT NOT NULL
        );
        "#
    );

    client.batch_execute(&ddl).await.map_err(|e| {
        PgError::from_query_err(
            format!("Failed to ensure state tables in schema '{schema_name}'"),
            &e,
        )
    })
}

pub async fn state_tables_exist(client: &Client, schema_name: &str) -> Result<bool> {
    for table_name in STATE_TABLES {
        let row = client
            .query_one(
                "SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = $1 AND table_name = $2
                )",
                &[&schema_name, &table_name],
            )
            .await
            .map_err(|e| {
                PgError::from_query_err(
                    format!("Failed to check table '{schema_name}.{table_name}'"),
                    &e,
                )
            })?;

        let table_exists: bool = row.get(0);
        if !table_exists {
            return Ok(false);
        }
    }

    Ok(true)
}
