use std::path::PathBuf;

use pg::column::ColumnInfo;

use crate::error::CliError;
use crate::paths::ProjectPaths;

/// Input for the pure schema content generator.
pub struct SchemaInput {
    pub schema: String,
    pub table: String,
    pub columns: Vec<ColumnInfo>,
}

/// Filter and reorder `all_columns` according to `config_columns`.
///
/// If `config_columns` is `None`, returns all columns in ordinal order.
/// If `config_columns` is `Some`, returns only the named columns in the
/// order they appear in the config, erroring if any are missing.
pub fn resolve_schema_columns(
    all_columns: &[ColumnInfo],
    config_columns: Option<&[String]>,
) -> Result<Vec<ColumnInfo>, String> {
    match config_columns {
        None => Ok(all_columns.to_vec()),
        Some(names) => {
            let mut seen = std::collections::HashSet::new();
            let mut result = Vec::with_capacity(names.len());
            for name in names {
                if !seen.insert(name.as_str()) {
                    return Err(format!("duplicate column '{name}' in config"));
                }
                let col = all_columns
                    .iter()
                    .find(|c| c.name == *name)
                    .ok_or_else(|| format!("column '{name}' not found in table"))?;
                result.push(col.clone());
            }
            Ok(result)
        }
    }
}

/// Map a Postgres `udt_name` to its TypeScript type.
fn ts_type(udt_name: &str) -> &'static str {
    match udt_name {
        "int2" | "int4" | "float4" | "float8" => "number",
        "int8" | "numeric" => "string", // bigint/numeric — can overflow JS number
        "bool" => "boolean",
        "json" | "jsonb" => "unknown",
        _ => "string",
    }
}

/// Generate the parse expression for a column at `index`, given its Postgres type.
fn ts_parse_expr(udt_name: &str, index: usize) -> String {
    let col = format!("cols[{index}]");
    match udt_name {
        "int2" | "int4" | "float4" | "float8" => {
            format!("{col} === null ? null : Number({col})")
        }
        "bool" => format!("{col} === null ? null : {col} === \"true\""),
        "json" | "jsonb" => format!("{col} === null ? null : JSON.parse({col})"),
        _ => format!("{col} ?? null"),
    }
}

/// Escape a string for use inside a TS double-quoted string literal.
fn ts_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                out.push_str(&format!("\\u{{{:04x}}}", c as u32));
            }
            _ => out.push(c),
        }
    }
    out
}

/// Return true if `name` is a valid bare JS/TS property key (identifier).
fn is_valid_js_ident(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let mut chars = name.chars();
    let first = chars.next().unwrap();
    if !first.is_ascii_alphabetic() && first != '_' && first != '$' {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

/// Render a column name as a TS property key, quoting if needed.
fn ts_property_key(name: &str) -> String {
    if is_valid_js_ident(name) {
        name.to_string()
    } else {
        format!("\"{}\"", ts_escape(name))
    }
}

/// Generate the contents of a `schema.ts` file from the given input.
pub fn generate_schema_content(input: &SchemaInput) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by `puffgres generate`. Do not edit.\n");
    out.push_str(&format!("// Source: {}.{}\n", input.schema, input.table));
    out.push('\n');

    // columns array
    let col_names: Vec<&str> = input.columns.iter().map(|c| c.name.as_str()).collect();
    let col_literals: Vec<String> = col_names
        .iter()
        .map(|n| format!("\"{}\"", ts_escape(n)))
        .collect();
    out.push_str(&format!(
        "export const columns = [{}] as const;\n",
        col_literals.join(", ")
    ));
    out.push_str("export type ColumnName = (typeof columns)[number];\n");
    out.push('\n');

    // Row type
    out.push_str("export type Row = {\n");
    for col in &input.columns {
        let ts = ts_type(&col.udt_name);
        out.push_str(&format!(
            "  {}: {} | null;\n",
            ts_property_key(&col.name),
            ts
        ));
    }
    out.push_str("};\n");
    out.push('\n');

    // columnIndex object
    out.push_str("export const columnIndex = {\n");
    for (i, col) in input.columns.iter().enumerate() {
        out.push_str(&format!(
            "  {}: {}, // {}\n",
            ts_property_key(&col.name),
            i,
            col.udt_name
        ));
    }
    out.push_str("} as const;\n");
    out.push('\n');

    // parseRow function
    out.push_str("export function parseRow(cols: (string | null)[]): Row {\n");
    out.push_str("  return {\n");
    for (i, col) in input.columns.iter().enumerate() {
        out.push_str(&format!(
            "    {}: {},\n",
            ts_property_key(&col.name),
            ts_parse_expr(&col.udt_name, i)
        ));
    }
    out.push_str("  };\n");
    out.push_str("}\n");

    out
}

pub fn run(paths: &ProjectPaths, database_url: &str) -> Result<(), CliError> {
    let rt = tokio::runtime::Runtime::new()
        .map_err(|e| CliError::Generate(format!("failed to create async runtime: {e}")))?;
    rt.block_on(run_async(paths, database_url))
}

pub async fn run_async(paths: &ProjectPaths, database_url: &str) -> Result<(), CliError> {
    let loader = config::ConfigLoader::new(&paths.configs);
    let configs = loader.load_all()?;

    if configs.is_empty() {
        println!("No config files found in configs/");
        return Ok(());
    }

    // Filter out tombstoned configs
    let active_configs: Vec<_> = configs
        .into_iter()
        .filter(|(path, _)| {
            let tombstone = path.parent().unwrap().join("tombstone.toml");
            !tombstone.exists()
        })
        .collect();

    if active_configs.is_empty() {
        println!("All configs are tombstoned, nothing to generate.");
        return Ok(());
    }

    let pg_client = pg::connect::connect(database_url)
        .await
        .map_err(|e| CliError::Generate(format!("failed to connect to postgres: {e}")))?;

    let mut generated = 0;

    for (config_path, config) in &active_configs {
        let config_dir = config_path.parent().unwrap();
        let qualified = format!("{}.{}", config.source.schema, config.source.table);

        let all_columns = pg::column::resolve_column_info(
            &pg_client,
            &config.source.schema,
            &config.source.table,
        )
        .await
        .map_err(|e| CliError::Generate(format!("{qualified}: {e}")))?;

        let columns =
            resolve_schema_columns(&all_columns, config.columns.as_deref()).map_err(|e| {
                CliError::Generate(format!("{qualified} (config {}): {e}", config.name))
            })?;

        let input = SchemaInput {
            schema: config.source.schema.clone(),
            table: config.source.table.clone(),
            columns,
        };

        let content = generate_schema_content(&input);
        let schema_path = config_dir.join("schema.ts");
        std::fs::write(&schema_path, &content).map_err(|e| {
            CliError::Generate(format!("failed to write {}: {e}", schema_path.display()))
        })?;

        println!("  {:<12} wrote {}", config.name, schema_path.display());
        generated += 1;
    }

    println!("\nGenerated {generated} schema file(s).");
    Ok(())
}

/// Verify all non-tombstoned configs have up-to-date schema.ts files.
///
/// Returns a list of config names with problems (missing or outdated schema).
pub async fn verify_schemas(
    configs: &[(PathBuf, config::Config)],
    database_url: &str,
) -> Result<Vec<String>, CliError> {
    let active_configs: Vec<_> = configs
        .iter()
        .filter(|(path, _)| {
            let tombstone = path.parent().unwrap().join("tombstone.toml");
            !tombstone.exists()
        })
        .collect();

    if active_configs.is_empty() {
        return Ok(Vec::new());
    }

    let pg_client = pg::connect::connect(database_url)
        .await
        .map_err(|e| CliError::Generate(format!("failed to connect to postgres: {e}")))?;

    let mut errors = Vec::new();

    for (config_path, config) in &active_configs {
        let config_dir = config_path.parent().unwrap();
        let schema_path = config_dir.join("schema.ts");
        let qualified = format!("{}.{}", config.source.schema, config.source.table);

        let all_columns = pg::column::resolve_column_info(
            &pg_client,
            &config.source.schema,
            &config.source.table,
        )
        .await
        .map_err(|e| CliError::Generate(format!("{qualified}: {e}")))?;

        let columns =
            resolve_schema_columns(&all_columns, config.columns.as_deref()).map_err(|e| {
                CliError::Generate(format!("{qualified} (config {}): {e}", config.name))
            })?;

        let input = SchemaInput {
            schema: config.source.schema.clone(),
            table: config.source.table.clone(),
            columns,
        };

        let expected = generate_schema_content(&input);

        match std::fs::read_to_string(&schema_path) {
            Ok(actual) if actual == expected => {}
            Ok(_) => {
                errors.push(format!(
                    "{}: schema.ts is outdated. Run `puffgres generate`",
                    config.name
                ));
            }
            Err(_) => {
                errors.push(format!(
                    "{}: schema.ts is missing. Run `puffgres generate`",
                    config.name
                ));
            }
        }
    }

    Ok(errors)
}

#[cfg(test)]
mod tests {
    use super::*;
    use pg::column::ColumnInfo;

    fn sample_columns() -> Vec<ColumnInfo> {
        vec![
            ColumnInfo {
                name: "id".to_string(),
                udt_name: "int4".to_string(),
                ordinal_position: 1,
            },
            ColumnInfo {
                name: "name".to_string(),
                udt_name: "text".to_string(),
                ordinal_position: 2,
            },
            ColumnInfo {
                name: "email".to_string(),
                udt_name: "varchar".to_string(),
                ordinal_position: 3,
            },
        ]
    }

    #[test]
    fn generate_schema_content_basic() {
        let input = SchemaInput {
            schema: "public".to_string(),
            table: "users".to_string(),
            columns: sample_columns(),
        };
        let content = generate_schema_content(&input);

        assert!(content.contains("// Auto-generated by `puffgres generate`. Do not edit."));
        assert!(content.contains("// Source: public.users"));
        assert!(content.contains(r#"export const columns = ["id", "name", "email"] as const;"#));
        assert!(content.contains("export type ColumnName = (typeof columns)[number];"));
        // Row type with proper TS types
        assert!(content.contains("export type Row = {"));
        assert!(content.contains("id: number | null;"));
        assert!(content.contains("name: string | null;"));
        assert!(content.contains("email: string | null;"));
        // columnIndex
        assert!(content.contains("id: 0, // int4"));
        assert!(content.contains("name: 1, // text"));
        assert!(content.contains("email: 2, // varchar"));
        // parseRow returns Row with typed parsing
        assert!(content.contains("export function parseRow(cols: (string | null)[]): Row {"));
        assert!(content.contains("id: cols[0] === null ? null : Number(cols[0]),"));
        assert!(content.contains("name: cols[1] ?? null,"));
        assert!(content.contains("email: cols[2] ?? null,"));
    }

    #[test]
    fn generate_schema_content_single_column() {
        let input = SchemaInput {
            schema: "app".to_string(),
            table: "items".to_string(),
            columns: vec![ColumnInfo {
                name: "id".to_string(),
                udt_name: "uuid".to_string(),
                ordinal_position: 1,
            }],
        };
        let content = generate_schema_content(&input);

        assert!(content.contains("// Source: app.items"));
        assert!(content.contains(r#"export const columns = ["id"] as const;"#));
        assert!(content.contains("id: 0, // uuid"));
    }

    #[test]
    fn resolve_schema_columns_no_filter() {
        let all = sample_columns();
        let result = resolve_schema_columns(&all, None).unwrap();
        assert_eq!(result.len(), 3);
        assert_eq!(result[0].name, "id");
        assert_eq!(result[1].name, "name");
        assert_eq!(result[2].name, "email");
    }

    #[test]
    fn resolve_schema_columns_with_filter() {
        let all = sample_columns();
        let filter = vec!["email".to_string(), "id".to_string()];
        let result = resolve_schema_columns(&all, Some(&filter)).unwrap();
        assert_eq!(result.len(), 2);
        assert_eq!(result[0].name, "email");
        assert_eq!(result[1].name, "id");
    }

    #[test]
    fn resolve_schema_columns_missing_column_errors() {
        let all = sample_columns();
        let filter = vec!["nonexistent".to_string()];
        let err = resolve_schema_columns(&all, Some(&filter)).unwrap_err();
        assert!(err.contains("nonexistent"));
    }

    #[test]
    fn resolve_schema_columns_rejects_duplicates() {
        let all = sample_columns();
        let filter = vec!["id".to_string(), "id".to_string()];
        let err = resolve_schema_columns(&all, Some(&filter)).unwrap_err();
        assert!(err.contains("duplicate"));
    }

    #[test]
    fn numeric_type_maps_to_string() {
        assert_eq!(ts_type("numeric"), "string");
    }

    #[test]
    fn bool_parse_uses_true_string() {
        let expr = ts_parse_expr("bool", 0);
        assert!(expr.contains(r#"=== "true""#), "got: {expr}");
    }

    #[test]
    fn numeric_parse_passes_through_as_string() {
        let expr = ts_parse_expr("numeric", 0);
        // Should NOT contain Number()
        assert!(!expr.contains("Number("), "got: {expr}");
        assert!(expr.contains("?? null"), "got: {expr}");
    }

    #[test]
    fn special_column_names_are_quoted() {
        let input = SchemaInput {
            schema: "public".to_string(),
            table: "test".to_string(),
            columns: vec![
                ColumnInfo {
                    name: "user-id".to_string(),
                    udt_name: "int4".to_string(),
                    ordinal_position: 1,
                },
                ColumnInfo {
                    name: "first name".to_string(),
                    udt_name: "text".to_string(),
                    ordinal_position: 2,
                },
            ],
        };
        let content = generate_schema_content(&input);

        // Column names with special chars should be quoted in all positions
        assert!(
            content.contains(r#""user-id": number | null;"#),
            "Row type should quote user-id"
        );
        assert!(
            content.contains(r#""first name": string | null;"#),
            "Row type should quote first name"
        );
        assert!(
            content.contains(r#""user-id": 0,"#),
            "columnIndex should quote user-id"
        );
        assert!(
            content.contains(r#""first name": 1,"#),
            "columnIndex should quote first name"
        );
    }

    #[test]
    fn column_names_with_quotes_are_escaped() {
        let input = SchemaInput {
            schema: "public".to_string(),
            table: "test".to_string(),
            columns: vec![ColumnInfo {
                name: r#"a"b"#.to_string(),
                udt_name: "text".to_string(),
                ordinal_position: 1,
            }],
        };
        let content = generate_schema_content(&input);
        // The column array literal should have the quote escaped
        assert!(
            content.contains(r#""a\"b""#),
            "column literal should escape quotes: {content}"
        );
    }

    #[test]
    fn valid_identifiers_are_not_quoted() {
        assert!(is_valid_js_ident("id"));
        assert!(is_valid_js_ident("_private"));
        assert!(is_valid_js_ident("$money"));
        assert!(is_valid_js_ident("camelCase123"));
        assert!(!is_valid_js_ident(""));
        assert!(!is_valid_js_ident("user-id"));
        assert!(!is_valid_js_ident("first name"));
        assert!(!is_valid_js_ident("123abc"));
    }
}
