use std::path::PathBuf;

use pg::column::ColumnInfo;

use crate::error::CliError;
use crate::paths::ProjectPaths;
use crate::tombstones::has_on_disk_tombstone;

/// Input for the pure schema content generator.
pub struct SchemaInput {
    pub schema: String,
    pub table: String,
    pub columns: Vec<ColumnInfo>,
}

/// Filter and reorder `all_columns` according to `config_columns`.
///
/// If `config_columns` is `None`, returns all columns in ordinal order.
/// If `config_columns` is `Some`, returns only the named columns in the
/// order they appear in the config, erroring if any are missing.
pub fn resolve_schema_columns(
    all_columns: &[ColumnInfo],
    config_columns: Option<&[String]>,
) -> Result<Vec<ColumnInfo>, String> {
    match config_columns {
        None => Ok(all_columns.to_vec()),
        Some(names) => {
            let mut seen = std::collections::HashSet::new();
            let mut result = Vec::with_capacity(names.len());
            for name in names {
                if !seen.insert(name.as_str()) {
                    return Err(format!("duplicate column '{name}' in config"));
                }
                let col = all_columns
                    .iter()
                    .find(|c| c.name == *name)
                    .ok_or_else(|| format!("column '{name}' not found in table"))?;
                result.push(col.clone());
            }
            Ok(result)
        }
    }
}

/// Map a Postgres scalar `udt_name` to its turbopuffer PrimitiveType.
fn tpuf_scalar_type(udt_name: &str) -> &'static str {
    match udt_name {
        "int2" | "int4" | "int8" => "int",
        "float4" | "float8" | "numeric" => "float",
        "bool" => "bool",
        "uuid" => "uuid",
        "json" | "jsonb" => "json",
        _ => "string",
    }
}

/// Map a Postgres `udt_name` to its turbopuffer type, handling arrays.
///
/// Array types are represented as `element_type[]` (e.g. `int4[]`, `text[]`).
fn tpuf_type(udt_name: &str) -> &'static str {
    if let Some(element) = udt_name.strip_suffix("[]") {
        return match tpuf_scalar_type(element) {
            "int" => "int[]",
            "float" => "float[]",
            "bool" => "bool[]",
            "uuid" => "uuid[]",
            "json" => "json[]",
            _ => "string[]",
        };
    }
    tpuf_scalar_type(udt_name)
}

/// Escape a string for use inside a TS double-quoted string literal.
fn ts_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                out.push_str(&format!("\\u{{{:04x}}}", c as u32));
            }
            _ => out.push(c),
        }
    }
    out
}

/// Generate the contents of a `schema.ts` file from the given input.
pub fn generate_schema_content(input: &SchemaInput) -> String {
    let mut out = String::new();

    out.push_str("/* eslint-disable */\n");
    out.push_str("// prettier-ignore\n");
    out.push_str("// Auto-generated by `puffgres generate`. Do not edit.\n");
    out.push_str(&format!("// Source: {}.{}\n", input.schema, input.table));
    out.push('\n');
    out.push_str("import { parseRow as parseRowInternal, parseRows as parseRowsInternal, type Column } from \"../../utils/puffgres\";\n");
    out.push('\n');

    // columns array
    out.push_str("export const columns = [\n");
    for col in &input.columns {
        out.push_str(&format!(
            "  {{ name: \"{}\", type: \"{}\" }},\n",
            ts_escape(&col.name),
            tpuf_type(&col.udt_name)
        ));
    }
    out.push_str("] as const satisfies readonly Column[];\n");
    out.push('\n');

    // bound parseRow / parseRows
    out.push_str(
        "export const parseRow = (cols: (string | null)[]) => parseRowInternal(columns, cols);\n",
    );
    out.push_str("export const parseRows = (rows: (string | null)[][]) => parseRowsInternal(columns, rows);\n");

    out
}

pub fn run(paths: &ProjectPaths, database_url: &str) -> Result<(), CliError> {
    let rt = tokio::runtime::Runtime::new()
        .map_err(|e| CliError::Generate(format!("failed to create async runtime: {e}")))?;
    rt.block_on(run_async(paths, database_url))
}

pub async fn run_async(paths: &ProjectPaths, database_url: &str) -> Result<(), CliError> {
    let loader = config::ConfigLoader::new(&paths.configs);
    let configs = loader.load_all()?;

    if configs.is_empty() {
        println!("No config files found in configs/");
        return Ok(());
    }

    // Filter out tombstoned configs
    let active_configs: Vec<_> = configs
        .into_iter()
        .filter(|(path, _)| !has_on_disk_tombstone(path))
        .collect();

    if active_configs.is_empty() {
        println!("All configs are tombstoned, nothing to generate.");
        return Ok(());
    }

    let pg_client = pg::connect::connect(database_url)
        .await
        .map_err(|e| CliError::Generate(format!("failed to connect to postgres: {e}")))?;

    let mut generated = 0;

    for (config_path, config) in &active_configs {
        let config_dir = config_path.parent().unwrap();
        let qualified = format!("{}.{}", config.source.schema, config.source.table);

        let all_columns = pg::column::resolve_column_info(
            &pg_client,
            &config.source.schema,
            &config.source.table,
        )
        .await
        .map_err(|e| CliError::Generate(format!("{qualified}: {e}")))?;

        let columns =
            resolve_schema_columns(&all_columns, config.columns.as_deref()).map_err(|e| {
                CliError::Generate(format!("{qualified} (config {}): {e}", config.name))
            })?;

        let input = SchemaInput {
            schema: config.source.schema.clone(),
            table: config.source.table.clone(),
            columns,
        };

        let content = generate_schema_content(&input);
        let schema_path = config_dir.join("schema.ts");
        std::fs::write(&schema_path, &content).map_err(|e| {
            CliError::Generate(format!("failed to write {}: {e}", schema_path.display()))
        })?;

        println!("  {:<12} wrote {}", config.name, schema_path.display());
        generated += 1;
    }

    println!("\nGenerated {generated} schema file(s).");
    Ok(())
}

/// Verify all non-tombstoned configs have up-to-date schema.ts files.
///
/// Returns a list of config names with problems (missing or outdated schema).
pub async fn verify_schemas(
    configs: &[(PathBuf, config::Config)],
    database_url: &str,
) -> Result<Vec<String>, CliError> {
    let active_configs: Vec<_> = configs
        .iter()
        .filter(|(path, _)| !has_on_disk_tombstone(path))
        .collect();

    if active_configs.is_empty() {
        return Ok(Vec::new());
    }

    let pg_client = pg::connect::connect(database_url)
        .await
        .map_err(|e| CliError::Generate(format!("failed to connect to postgres: {e}")))?;

    let mut errors = Vec::new();

    for (config_path, config) in &active_configs {
        let config_dir = config_path.parent().unwrap();
        let schema_path = config_dir.join("schema.ts");
        let qualified = format!("{}.{}", config.source.schema, config.source.table);

        let all_columns = pg::column::resolve_column_info(
            &pg_client,
            &config.source.schema,
            &config.source.table,
        )
        .await
        .map_err(|e| CliError::Generate(format!("{qualified}: {e}")))?;

        let columns =
            resolve_schema_columns(&all_columns, config.columns.as_deref()).map_err(|e| {
                CliError::Generate(format!("{qualified} (config {}): {e}", config.name))
            })?;

        let input = SchemaInput {
            schema: config.source.schema.clone(),
            table: config.source.table.clone(),
            columns,
        };

        let expected = generate_schema_content(&input);

        match std::fs::read_to_string(&schema_path) {
            Ok(actual) if actual == expected => {}
            Ok(_) => {
                errors.push(format!(
                    "{}: schema.ts is outdated. Run `puffgres generate`",
                    config.name
                ));
            }
            Err(_) => {
                errors.push(format!(
                    "{}: schema.ts is missing. Run `puffgres generate`",
                    config.name
                ));
            }
        }
    }

    Ok(errors)
}

#[cfg(test)]
mod tests {
    use super::*;
    use pg::column::ColumnInfo;

    fn sample_columns() -> Vec<ColumnInfo> {
        vec![
            ColumnInfo {
                name: "id".to_string(),
                udt_name: "int4".to_string(),
                ordinal_position: 1,
            },
            ColumnInfo {
                name: "name".to_string(),
                udt_name: "text".to_string(),
                ordinal_position: 2,
            },
            ColumnInfo {
                name: "email".to_string(),
                udt_name: "varchar".to_string(),
                ordinal_position: 3,
            },
        ]
    }

    #[test]
    fn generate_schema_content_basic() {
        let input = SchemaInput {
            schema: "public".to_string(),
            table: "users".to_string(),
            columns: sample_columns(),
        };
        let content = generate_schema_content(&input);

        assert!(content.contains("// Auto-generated by `puffgres generate`. Do not edit."));
        assert!(content.contains("// Source: public.users"));
        assert!(content.contains("import { parseRow as parseRowInternal"));
        assert!(content.contains("type Column }"));
        // columns array with name/type pairs
        assert!(content.contains(r#"{ name: "id", type: "int" },"#));
        assert!(content.contains(r#"{ name: "name", type: "string" },"#));
        assert!(content.contains(r#"{ name: "email", type: "string" },"#));
        assert!(content.contains("as const satisfies readonly Column[]"));
        // bound parseRow/parseRows
        assert!(content.contains("export const parseRow ="));
        assert!(content.contains("export const parseRows ="));
        assert!(content.contains("parseRowInternal(columns, cols)"));
        assert!(content.contains("parseRowsInternal(columns, rows)"));
    }

    #[test]
    fn generate_schema_content_single_column() {
        let input = SchemaInput {
            schema: "app".to_string(),
            table: "items".to_string(),
            columns: vec![ColumnInfo {
                name: "id".to_string(),
                udt_name: "uuid".to_string(),
                ordinal_position: 1,
            }],
        };
        let content = generate_schema_content(&input);

        assert!(content.contains("// Source: app.items"));
        assert!(content.contains(r#"{ name: "id", type: "uuid" },"#));
    }

    #[test]
    fn resolve_schema_columns_no_filter() {
        let all = sample_columns();
        let result = resolve_schema_columns(&all, None).unwrap();
        assert_eq!(result.len(), 3);
        assert_eq!(result[0].name, "id");
        assert_eq!(result[1].name, "name");
        assert_eq!(result[2].name, "email");
    }

    #[test]
    fn resolve_schema_columns_with_filter() {
        let all = sample_columns();
        let filter = vec!["email".to_string(), "id".to_string()];
        let result = resolve_schema_columns(&all, Some(&filter)).unwrap();
        assert_eq!(result.len(), 2);
        assert_eq!(result[0].name, "email");
        assert_eq!(result[1].name, "id");
    }

    #[test]
    fn resolve_schema_columns_missing_column_errors() {
        let all = sample_columns();
        let filter = vec!["nonexistent".to_string()];
        let err = resolve_schema_columns(&all, Some(&filter)).unwrap_err();
        assert!(err.contains("nonexistent"));
    }

    #[test]
    fn resolve_schema_columns_rejects_duplicates() {
        let all = sample_columns();
        let filter = vec!["id".to_string(), "id".to_string()];
        let err = resolve_schema_columns(&all, Some(&filter)).unwrap_err();
        assert!(err.contains("duplicate"));
    }

    #[test]
    fn tpuf_type_mappings() {
        assert_eq!(tpuf_type("int4"), "int");
        assert_eq!(tpuf_type("int8"), "int");
        assert_eq!(tpuf_type("float8"), "float");
        assert_eq!(tpuf_type("numeric"), "float");
        assert_eq!(tpuf_type("bool"), "bool");
        assert_eq!(tpuf_type("uuid"), "uuid");
        assert_eq!(tpuf_type("json"), "json");
        assert_eq!(tpuf_type("jsonb"), "json");
        assert_eq!(tpuf_type("text"), "string");
        assert_eq!(tpuf_type("varchar"), "string");
    }

    #[test]
    fn tpuf_type_array_mappings() {
        assert_eq!(tpuf_type("int4[]"), "int[]");
        assert_eq!(tpuf_type("int8[]"), "int[]");
        assert_eq!(tpuf_type("float8[]"), "float[]");
        assert_eq!(tpuf_type("numeric[]"), "float[]");
        assert_eq!(tpuf_type("bool[]"), "bool[]");
        assert_eq!(tpuf_type("uuid[]"), "uuid[]");
        assert_eq!(tpuf_type("json[]"), "json[]");
        assert_eq!(tpuf_type("jsonb[]"), "json[]");
        assert_eq!(tpuf_type("text[]"), "string[]");
        assert_eq!(tpuf_type("varchar[]"), "string[]");
    }

    #[test]
    fn generate_schema_content_with_array_columns() {
        let input = SchemaInput {
            schema: "public".to_string(),
            table: "items".to_string(),
            columns: vec![
                ColumnInfo {
                    name: "id".to_string(),
                    udt_name: "int4".to_string(),
                    ordinal_position: 1,
                },
                ColumnInfo {
                    name: "tags".to_string(),
                    udt_name: "text[]".to_string(),
                    ordinal_position: 2,
                },
                ColumnInfo {
                    name: "scores".to_string(),
                    udt_name: "float8[]".to_string(),
                    ordinal_position: 3,
                },
            ],
        };
        let content = generate_schema_content(&input);

        assert!(content.contains(r#"{ name: "id", type: "int" },"#));
        assert!(content.contains(r#"{ name: "tags", type: "string[]" },"#));
        assert!(content.contains(r#"{ name: "scores", type: "float[]" },"#));
    }

    #[test]
    fn special_column_names_are_escaped() {
        let input = SchemaInput {
            schema: "public".to_string(),
            table: "test".to_string(),
            columns: vec![
                ColumnInfo {
                    name: "user-id".to_string(),
                    udt_name: "int4".to_string(),
                    ordinal_position: 1,
                },
                ColumnInfo {
                    name: r#"a"b"#.to_string(),
                    udt_name: "text".to_string(),
                    ordinal_position: 2,
                },
            ],
        };
        let content = generate_schema_content(&input);

        assert!(
            content.contains(r#"name: "user-id""#),
            "should contain user-id: {content}"
        );
        assert!(
            content.contains(r#"name: "a\"b""#),
            "should escape quotes: {content}"
        );
    }
}
